### ISSUE TITLE
When will the full code be disclosed

### ISSUE THREAD

**Issue by liuting20** [HVision-NKU/Cascade-CLIP#2]
hello, we can't find folder “mmseg” or "mmcv", so we can not study the excellent work.

**Comment by lyhisme** [comment]
Hello,

The mmseg and mmcv are not included in the repository but need to be installed separately. Please refer to the [INSTALL.md](https://github.com/HVision-NKU/Cascade-CLIP/blob/main/INSTALL.md) file for detailed installation instructions.

Best,
