### ISSUE TITLE
nga module

### ISSUE THREAD

**Issue by ybai111** [HVision-NKU/Cascade-CLIP#3]
Excuse me, where can I find the nga code?

**Comment by lyhisme** [comment]
Hello,

The "nga" code you're looking for can be found at [this line in the decode_seg.py file](https://github.com/HVision-NKU/Cascade-CLIP/blob/9954d717c7658211f2362a84780c7e56d2662a7c/models/decode_heads/decode_seg.py#L228). If you need further clarification or have additional questions, feel free to ask. 


Best,
